myblogapp/blog/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired
from myblogapp.models import Category
from wtforms.ext.sqlalchemy.fields import QuerySelectField

def enabled_categories():
    return Category.query.all()

class CategoryForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Add Category')

class PostForm(FlaskForm):
    category = QuerySelectField(query_factory=enabled_categories, allow_blank=True)
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Post Content', validators=[DataRequired()])
    img = FileField('Add Post Img', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Add Post')

myblogapp/blog/routes.py
from flask import render_template, redirect, url_for, Blueprint, request
from .forms import CategoryForm, PostForm
from myblogapp.models import Post, Category
from werkzeug.utils import secure_filename
import os
from myblogapp import app, db

blog = Blueprint('blog', __name__, template_folder='templates')

@blog.route('/admin/add-post', methods=['POST', 'GET'])
def post_add():
    form=PostForm()
    if form.validate_on_submit():
        file = request.files['img']
        post_img = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], post_img))

        new_post = Post(category=form.category.data, title=form.title.data, content=form.content.data, img=post_img)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('blog.post_add'))     
    return render_template('blog_post_add.html', form=form)

@blog.route('/admin/add-category', methods=['POST', 'GET'])
def cat_add():
    form=CategoryForm()
    cats=Category.query.all()
    if form.validate_on_submit():
        new_cat=Category(name=form.name.data)
        db.session.add(new_cat)
        db.session.commit()
        return redirect(url_for('blog.cat_add'))
    return render_template('blog_cat_add.html', form=form, cats=cats)

@blog.route('/admin/edit-category/<int:id>', methods=['POST', 'GET'])
def cat_edit(id):
    form=CategoryForm()
    selected_cat=Category.query.get(id)
    if request.method=='GET':
        form.name.data=selected_cat.name
    elif request.method=='POST':
        selected_cat.name=form.name.data
        db.session.commit()
        return redirect(url_for('blog.cat_add'))
    return render_template('blog_cat_add.html', form=form)


@blog.route('/admin/delete-category/<int:id>', methods=['POST', 'GET'])
def cat_delete(id):
    selected_cat=Category.query.get(id)
    db.session.delete(selected_cat)
    db.session.commit()
    return redirect(url_for('blog.cat_add'))

myblogapp/blog/templates/blog_cat_add.html
{% extends 'admin_layout.html' %}
{% block body %}
<div class="card">
    <div class="card-body"> 
        <div class="row">
            <div class="col-lg-12">
                <form method="POST" action="" novalidate enctype="multipart/form-data" class="default-form"> 
                    {{ form.hidden_tag() }}
                    <div class="form-group row">
                        {{ form.name.label(class="col-sm-2 col-form-label text-right") }}
                        <div class="col-sm-10">
                            {% if form.name.errors %}
                                {{ form.name(class="is-invalid form-control") }}
                                <div class="invalid-feedback">
                                    {% for error in form.name.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.name(class="form-control") }}
                            {% endif %}
                        </div>
                    </div>  
                    <div class="form-group row">
                        {{ form.submit(class="btn btn-primary", style="margin-left:15px;") }}
                    </div>                               
                </form>
            </div>
        </div>                                                                      
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped mb-0">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Category Name</th>
                                <th>Redaktə/Sil</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cat in cats %}
                                <tr>
                                    <td>{{ cat.id }}</td>
                                    <td>{{ cat.name }}</td>
                                    <td>
                                        <a href="{{url_for('blog.cat_edit', id = cat.id)}}" class="mr-2"><i class="fas fa-edit text-info font-16"></i></a>
                                        <a href="{{url_for('blog.cat_delete', id = cat.id)}}"><i class="fas fa-trash-alt text-danger font-16"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myblogapp/blog/templates/blog_post_add.html
{% extends 'admin_layout.html' %}
{% block body %}
<div class="card">
    <div class="card-body"> 
        <div class="row">
            <div class="col-lg-12">
                <form method="POST" action="" novalidate enctype="multipart/form-data" class="default-form"> 
                    {{ form.hidden_tag() }}
                    <div class="form-group row">
                        {{ form.category.label(class="col-sm-2 col-form-label text-right") }}
                        <div class="col-sm-10">
                            {{ form.category(class="form-control") }}
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ form.title.label(class="col-sm-2 col-form-label text-right") }}
                        <div class="col-sm-10">
                            {% if form.title.errors %}
                                {{ form.title(class="is-invalid form-control") }}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.title(class="form-control") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ form.content.label(class="col-sm-2 col-form-label text-right") }}
                        <div class="col-sm-10">
                            {% if form.content.errors %}
                                {{ form.content(class="is-invalid form-control") }}
                                <div class="invalid-feedback">
                                    {% for error in form.content.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.content(class="form-control") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ form.img.label(class="col-sm-2 col-form-label text-right") }}
                        {{ form.img(style="margin-left:12px; margin-top:5px;") }}
                        {% if form.img.errors %}
                            {% for error in form.img.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}
                    </div>    
                    <div class="form-group row">
                        {{ form.submit(class="btn btn-primary", style="margin-left:15px;") }}
                    </div>                               
                </form>
            </div>
        </div>                                                                      
    </div>
</div>
{% endblock %}