myblogapp/admin/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class SliderForm(FlaskForm):
    text = TextAreaField('Slider Text', validators=[DataRequired()])
    img = FileField('Add Slider Img', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Add Slider')

myblogapp/admin/routes.py
from flask import render_template, redirect, url_for, Blueprint, request
from .forms import SliderForm
from myblogapp.models import Slider
from werkzeug.utils import secure_filename
import os
from myblogapp import app, db

admin = Blueprint('admin', __name__, template_folder='templates')

@admin.route('/admin')
def index():
    return render_template('admin_layout.html')

@admin.route('/admin/add-slider', methods=['POST', 'GET'])
def add_slider():
    form = SliderForm()
    if form.validate_on_submit():
        file = request.files['img']
        slider_img = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], slider_img))

        new_slider = Slider(text=form.text.data, img=slider_img)
        db.session.add(new_slider)
        db.session.commit()
        return redirect(url_for('user.index'))
    return render_template('admin_slider_add.html', form=form)

myblogapp/admin/templates/admin_layout.html
<!DOCTYPE html>
<html lang="az">

    <head>
        <meta charset="utf-8" />
        <title>Admin Panel</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta content="Admin Panel" name="description" />
        <meta content="" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- App favicon -->
        <link rel="icon" href="{{ url_for('static', filename='admin/images/favicon-pragma.png') }}" type="image/x-icon">

        <!-- App css -->
        <link href="{{ url_for('static', filename='admin/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/jquery-ui.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='admin/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/metisMenu.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/app.min.css') }}" rel="stylesheet" type="text/css" />

        <link href="{{ url_for('static', filename='admin/css/jquery-ui.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='admin/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/metisMenu.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/app-material.min.css') }}" rel="stylesheet" type="text/css" />
        
        <!-- include summernote css/js -->
        <link href="{{ url_for('static', filename='summernote/summernote.min.css') }}" rel="stylesheet">
    </head>

    <body>
        <!-- leftbar-tab-menu -->
        <div class="leftbar-tab-menu">
            <div class="main-icon-menu">
                <a href="#" class="logo logo-metrica d-block text-center">
                    <span>
                        <img src="{{ url_for('static', filename='admin/images/favicon-pragma.png') }}" alt="logo-small" class="logo-sm">
                    </span>
                </a>
                <nav class="nav">

                    <a href="#PragmatechUsers" class="nav-link" data-toggle="tooltip-custom" data-placement="right"  data-trigger="hover" title="" data-original-title="Blog">
                        <i data-feather="users" class="align-self-center menu-icon icon-dual"></i>
                    </a><!--end MetricaUsers-->

                    <a href="#PragmatechPages" class="nav-link" data-toggle="tooltip-custom" data-placement="right" title="" data-original-title="Pages" data-trigger="hover">
                        <i data-feather="copy" class="align-self-center menu-icon icon-dual"></i>             
                    </a><!--end MetricaPages--> 

                </nav><!--end nav-->
            </div><!--end main-icon-menu-->

            <div class="main-menu-inner">
                <!-- LOGO -->
                <div class="topbar-left">
                    <a href="#" class="logo">
                        <span>
                            <h3 style="margin-top:24px;">Admin Panel</h3>
                        </span>
                    </a>                    
                </div>
                <!--end logo-->
                <div class="menu-body slimscroll">

                    <div id="PragmatechPages" class="main-icon-menu-pane">
                        <div class="title-box">
                            <h6 class="menu-title">Pages</h6>        
                        </div>
                        <ul class="nav">
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.add_slider') }}">Add Slider</a></li>
                        </ul>
                    </div><!-- end Pages -->

                    <div id="PragmatechUsers" class="main-icon-menu-pane">
                        <div class="title-box">
                            <h6 class="menu-title">Blog</h6>     
                        </div>
                        <ul class="nav">
                            <li class="nav-item"><a class="nav-link" href="{{url_for('blog.post_add')}}">Posts</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{url_for('blog.cat_add')}}">Category</a></li>
                        </ul>
                    </div><!-- end Pages -->

                </div><!--end menu-body-->
            </div><!-- end main-menu-inner-->
        </div>
        <!-- end leftbar-tab-menu-->

        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- Navbar -->
            <nav class="navbar-custom">
                <ul class="list-unstyled topbar-nav mb-0">
                    <li>
                        <a href="#">
                            <span class="responsive-logo">
                                <img src="{{ url_for('static', filename='admin/images/favicon-pragma.png') }}" alt="logo-small" class="logo-sm align-self-center" height="34">
                            </span>
                        </a>
                    </li>
                    <li>
                        <button class="button-menu-mobile nav-link">
                            <i data-feather="menu" class="align-self-center"></i>
                        </button>
                    </li>
                </ul>
            </nav>
            <!-- end navbar-->
        </div>
        <!-- Top Bar End -->

        <div class="page-wrapper">

            <!-- Page Content-->
            <div class="page-content-tab">

                <div class="container-fluid">
                    <!-- Page-Title -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title-box">
                                {% block body %}{% endblock %}
                            </div><!--end page-title-box-->
                        </div><!--end col-->
                    </div>
                    <!-- end page title end breadcrumb -->
                </div><!-- container -->
                <footer class="footer text-center text-sm-left">
                    &copy; 2020 Pragmatech
                </footer><!--end footer-->
            </div>
            <!-- end page content -->
        </div>
        <!-- end page-wrapper -->




        <!-- jQuery  -->
        <script src="{{ url_for('static', filename='admin/js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/jquery-ui.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/metismenu.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/waves.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/feather.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/jquery.slimscroll.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/summernote.js') }}"></script>

        <!-- App js -->
        <script src="{{ url_for('static', filename='summernote/summernote.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/app.js') }}"></script>

    </body>

</html>

myblogapp/admin/templates/admin_slider_add.html
{% extends 'admin_layout.html' %}
{% block body %}
<div class="card">
    <div class="card-body"> 
        <div class="row">
            <div class="col-lg-12">
                <form method="POST" action="" novalidate enctype="multipart/form-data" class="default-form"> 
                    {{ form.hidden_tag() }}
                    <div class="form-group row">
                        {{ form.text.label(class="col-sm-2 col-form-label text-right") }}
                        <div class="col-sm-10">
                            {% if form.text.errors %}
                                {{ form.text(class="is-invalid form-control") }}
                                <div class="invalid-feedback">
                                    {% for error in form.text.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.text(class="form-control") }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ form.img.label(class="col-sm-2 col-form-label text-right") }}
                        {{ form.img(style="margin-left:12px; margin-top:5px;") }}
                        {% if form.img.errors %}
                            {% for error in form.img.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}
                    </div>    
                    <div class="form-group row">
                        {{ form.submit(class="btn btn-primary", style="margin-left:15px;") }}
                    </div>                               
                </form>
            </div>
        </div>                                                                      
    </div>
</div>
{% endblock %}